version: "3.9"

services:
  web:
    build: .
    container_name: sample_app.api
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/tmp
      - gem-data:/usr/local/bundle
    working_dir: /app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - sample_app-networks
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@5432:5432/rails_boilerplate_development
      POSTGRES_HOST_AUTH_METHOD: trust
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    container_name: sample_app.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sample_app-networks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server
    container_name: sample_app.redis
    volumes:
      - redis-data:/var/shared/redis
    networks:
      - sample_app-networks

networks:
  sample_app-networks:
    name: sample_app
    external: true

volumes:
  db-data:
  gem-data:
  redis-data:
