version: "3.9"

services:
  web:
    build: .
    container_name: api.api
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/tmp
      - gem-data:/usr/local/bundle
    working_dir: /app
    command: bundle exec puma -C config/puma.rb -e production
    networks:
      - api-networks
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@5432:5432/api_production
      POSTGRES_HOST_AUTH_METHOD: trust
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    container_name: api.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - api-networks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server
    container_name: api.redis
    volumes:
      - redis-data:/var/shared/redis
    networks:
      - api-networks

networks:
  api-networks:
    name: api
    external: true

volumes:
  db-data:
  gem-data:
  redis-data:
